# @package _global_

defaults:
  - ddppo_pointnav
  - /habitat/task/measurements:
    - top_down_map
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor
  - _self_

habitat_baselines:
  evaluate: true
  load_resume_state_config: false
  checkpoint_folder: "data/new_checkpoints_pretrained_eval_tmp"
  num_environments: 1
  test_episode_count: 10
  video_dir: "videos/ddppo_pretrained_eval_tdm"
  eval:
    should_load_ckpt: false
    video_option: ["disk"]
  rl:
    ddppo:
      pretrained: true
      pretrained_weights: "data/ddppo-models/gibson-2plus-resnet50.pth"

habitat:
  gym:
    obs_keys:
      - depth
      - pointgoal_with_gps_compass
  task:
    measurements:
      top_down_map:
        fog_of_war:
          draw: true
        draw_shortest_path: true
